version: "3.8"
services:
  api-service:
    build: .
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: proyek
      MYSQL_USERNAME: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes